# Generated by Django 4.1.5 on 2023-01-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_albums_photo_alter_musicians_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='music.musicians'),
        ),
    ]
