# Generated by Django 4.1.5 on 2023-01-25 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_albums_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.musicians'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='photo',
            field=models.ImageField(upload_to='photos/albums/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='musicians',
            name='photo',
            field=models.ImageField(upload_to='photos/musicians/%Y/%m/%d/'),
        ),
    ]
